# HEADER --------------------------------------------
#
# Author: Charles Cunningham
# Email: charles.cunningham@york.ac.uk
# 
# Script Name: Project Euler problem 2 solution
#
# Script Description: Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the 
# previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values 
# do not exceed four million, find the sum of the even-valued terms.
#

# SET PARAMETERS ------------------------------------

# Fibonacci numbers cannot exceed this value
maxN = 4000000

### CODE --------------------------------------------

# Set initial Fibonacci list
fibList <- c(1,2)

# While the last Fibonacci value is below maxN...
while ( fibList[length(fibList)] < maxN) {
  
  # Create a new Fibonacci number (sum of previous two Fibonacci numbers)...
  fibN <- sum( fibList[length(fibList) - 1],
               fibList[length(fibList)])
  
  # ...and add to list
  fibList <- c(fibList, fibN)
  }

# Find even values, and drop last value as over maxN
fibListEven <- fibList[ fibList %% 2 == 0 &
                          fibList < maxN]

# Sum to find solution
sum(fibListEven)