# HEADER --------------------------------------------
#
# Author: Charles Cunningham
# Email: charles.cunningham@york.ac.uk
# 
# Script Name: Project Euler problem 12 solution
#
# Script Description: Highly divisible triangular number
#
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
# The first ten terms would be:
#
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
# Let us list the factors of the first seven triangle numbers:
#
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
#
# What is the value of the first triangle number to have over five hundred 
# divisors?

# SET PARAMETERS ----------------------------------

# Set threshold for number of divisors of triangle numbers,
# i.e. we are finding the triangle number with more than nDivThresh divisors
nDivThresh <- 500

### CODE ------------------------------------------

### Set objects -----------------------------------

# Current triangular number
tNum <- 0

# Number of divisors of triangle number
nDiv <-  0

# Natural number iterator
i <- 1

### Loop to find triangle number -----------------

# While the number of divisors is under the threshold...
while (nDiv <= nDivThresh) {
  
  # Add i to tNum to create the next triangular number
  tNum <- tNum + i
  
  # List the values between 1 and the square root of tNum
  # (N.B. By only looking up to square root this speeds up process hugely,
  # we find complementary values > square root later)
  nCheck <- c(1: floor(sqrt(tNum)))
  
  # Find values of nCheck which are divisors (i.e. tNum divisible by them)
  div <- nCheck[tNum %% nCheck == 0]
  
  # Find complementary values of div (i.e. divisors > square root)
  divPair <- tNum / div
  
  # Combine div and divPair
  allDiv <- c(div, divPair)
  
  # Remove any duplicate divisors, and find number of divisors
  nDiv <- length(unique(allDiv))
  
  # Add one to natural number iterator
  i <-  i + 1

}
  
# Return solution
print(tNum)
